
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  namespace: hello-world-ns
  labels:
    name: hello-world-service
spec:
  type: NodePort
  selector:
    component: hello-world
  ports:
    - name: hello-world-port
      protocol: TCP
      port: 8080
      targetPort: 8080
      
